nelmio_api_doc:
    documentation:
        info:
            title: bileMo
            description: A phone shop api
            version: 1.0.0

        paths:
            /api/login:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
            /api/users/:
                post: 
                    tags:  
                       - users
                    requestBody:    
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/User'
                                    
                                

        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: admin@gmail.com
                        password:
                            type: string
                            default: 1234
                User: 
                    type: object
                    properties:
                        firstname:
                            type: string
                            default: john
                        lastname:
                            type: string
                            default: doe 
                        username:
                            type: string
                            default: john_doe@gmail.com
                        role:
                            type: string
                            default: ROLE_USER
                        password:
                            type: string
                            default: my_password
                        client: 
                            type: int 
                            default: 1
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization 
        security:
            - bearerAuth: []

    areas: 
        path_patterns:
            - ^/api(?!/doc$) 

    
