controllers:
    resource: ../src/Controller/
    type: attribute

login_check:
    path: /login_check

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }


